id: P003071
initial_creation_type: ocr
created_at: 26/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W21508
  title: བཀའ་མ་ཤིན་ཏུ་རྒྱས་པ།
  author: ''
  volumes:
    a939e4fe95354f108cdab93ea09495e0:
      image_group_id: I1KG8608
      title: ''
      volume_number: 1
      total_pages: 758
      base_file: v001.txt
    184b22c4b97c44fa981481bae4a011ee:
      image_group_id: I1KG8609
      title: ''
      volume_number: 2
      total_pages: 874
      base_file: v002.txt
    c740895db075465597d039e502656b0d:
      image_group_id: I1KG8610
      title: ''
      volume_number: 3
      total_pages: 718
      base_file: v003.txt
    52dc1c45fef04429b4c967ca11d8359b:
      image_group_id: I1KG8611
      title: ''
      volume_number: 4
      total_pages: 776
      base_file: v004.txt
    07b9cfe3ee3e4d50861b646287b542a5:
      image_group_id: I1KG8612
      title: ''
      volume_number: 5
      total_pages: 566
      base_file: v005.txt
    5708d75eba7047cbb6a41fba110ad54e:
      image_group_id: I1KG8613
      title: ''
      volume_number: 6
      total_pages: 638
      base_file: v006.txt
    4bbc5ae218f84c36a42a2b31dad28c43:
      image_group_id: I1KG8614
      title: ''
      volume_number: 7
      total_pages: 700
      base_file: v007.txt
    622fa9afc4324a45b7e3002732d83e07:
      image_group_id: I1KG8615
      title: ''
      volume_number: 8
      total_pages: 680
      base_file: v008.txt
    8d3bfddf78044d6dbffb74b2071c5432:
      image_group_id: I1KG8616
      title: ''
      volume_number: 9
      total_pages: 670
      base_file: v009.txt
    c6be200a3971481086eef046a7b910ec:
      image_group_id: I1KG8617
      title: ''
      volume_number: 10
      total_pages: 652
      base_file: v010.txt
    1fc8082dd59c4211b7d233dfd1e5166c:
      image_group_id: I1KG8618
      title: ''
      volume_number: 11
      total_pages: 530
      base_file: v011.txt
    6dc2e9ac0d0a428f88e30def493236bb:
      image_group_id: I1KG8619
      title: ''
      volume_number: 12
      total_pages: 646
      base_file: v012.txt
    c1b62abd73eb4fc6b2095f73565ab9b7:
      image_group_id: I1KG8620
      title: ''
      volume_number: 13
      total_pages: 688
      base_file: v013.txt
    3acc626b8b3b43329e763fb6e599795b:
      image_group_id: I1KG8621
      title: ''
      volume_number: 14
      total_pages: 664
      base_file: v014.txt
    30104c5ba82241a6b966a999fac19a45:
      image_group_id: I1KG8622
      title: ''
      volume_number: 15
      total_pages: 708
      base_file: v015.txt
    1a01f17484d24bca8c672f9058722696:
      image_group_id: I1KG8623
      title: ''
      volume_number: 16
      total_pages: 694
      base_file: v016.txt
    f49e47c928f5427d911d3e161b9ad9d5:
      image_group_id: I1KG8624
      title: ''
      volume_number: 17
      total_pages: 626
      base_file: v017.txt
    fd51916512c14e37bbc7a9da1e926d19:
      image_group_id: I1KG8625
      title: ''
      volume_number: 18
      total_pages: 654
      base_file: v018.txt
    523b616be6aa4b3eb205c44cf992cfd6:
      image_group_id: I1KG8626
      title: ''
      volume_number: 19
      total_pages: 642
      base_file: v019.txt
    1cb993e3efd44ffeadff550397a1f7be:
      image_group_id: I1KG8627
      title: ''
      volume_number: 20
      total_pages: 680
      base_file: v020.txt
    d5e5e66c9f794b9cbdb67780c7b2b14f:
      image_group_id: I1KG8628
      title: ''
      volume_number: 21
      total_pages: 798
      base_file: v021.txt
    eac03879590741619fb56ece69c2fc60:
      image_group_id: I1KG8629
      title: ''
      volume_number: 22
      total_pages: 650
      base_file: v022.txt
    00a530be5f1b48a1af8d95ca2ab5507a:
      image_group_id: I1KG8630
      title: ''
      volume_number: 23
      total_pages: 622
      base_file: v023.txt
    0f31ca807c7a4b52becd334c3de65d4b:
      image_group_id: I1KG8631
      title: ''
      volume_number: 24
      total_pages: 582
      base_file: v024.txt
    426438a14125426d9ea29b9a6be67a38:
      image_group_id: I1KG8632
      title: ''
      volume_number: 25
      total_pages: 438
      base_file: v025.txt
    81af06737b4248be8669e42e19e31d33:
      image_group_id: I1KG8633
      title: ''
      volume_number: 26
      total_pages: 686
      base_file: v026.txt
    ff92c340cb414d3ab9b4d9b7b654d908:
      image_group_id: I1KG8634
      title: ''
      volume_number: 27
      total_pages: 474
      base_file: v027.txt
    b3428160018945dfb1f53ab57f04e5ca:
      image_group_id: I1KG8635
      title: ''
      volume_number: 28
      total_pages: 716
      base_file: v028.txt
    485986dc2dd14de28a6e8e41e1e08990:
      image_group_id: I1KG8636
      title: ''
      volume_number: 29
      total_pages: 492
      base_file: v029.txt
    67bd53c6d48341c2937ee32424e80407:
      image_group_id: I1KG8637
      title: ''
      volume_number: 30
      total_pages: 544
      base_file: v030.txt
    75646acfbc594b1eb6678e3071dec0d6:
      image_group_id: I1KG8638
      title: ''
      volume_number: 31
      total_pages: 664
      base_file: v031.txt
    b572b733821c40b2ae5622166e4caa23:
      image_group_id: I1KG8639
      title: ''
      volume_number: 32
      total_pages: 718
      base_file: v032.txt
    956ff670dd2c4d23a8b3c4a7cb34a67c:
      image_group_id: I1KG8640
      title: ''
      volume_number: 33
      total_pages: 444
      base_file: v033.txt
    b5b68ffa940f471093975976a97bc2ea:
      image_group_id: I1KG8641
      title: ''
      volume_number: 34
      total_pages: 498
      base_file: v034.txt
    049a3db00488427398ada8b3dab6a792:
      image_group_id: I1KG8642
      title: ''
      volume_number: 35
      total_pages: 594
      base_file: v035.txt
    7254987f143b494999cb4c07fc91a6b0:
      image_group_id: I1KG8643
      title: ''
      volume_number: 36
      total_pages: 564
      base_file: v036.txt
    d8c2dbd8656e416f955ec43ed9998758:
      image_group_id: I1KG8644
      title: ''
      volume_number: 37
      total_pages: 678
      base_file: v037.txt
    5359ca310c3942f0873f1580bb8dddd4:
      image_group_id: I1KG8645
      title: ''
      volume_number: 38
      total_pages: 576
      base_file: v038.txt
    19e65b2129684699922191c1d6d278a2:
      image_group_id: I1KG8646
      title: ''
      volume_number: 39
      total_pages: 604
      base_file: v039.txt
    4378a4616f98432e94b2915bf0cd36c9:
      image_group_id: I1KG8647
      title: ''
      volume_number: 40
      total_pages: 858
      base_file: v040.txt
    2f9d1d4e3558478a89c5db46b08e8420:
      image_group_id: I1KG8648
      title: ''
      volume_number: 41
      total_pages: 890
      base_file: v041.txt
    5bb646f9b53f4dbeb9005ffaac9147a4:
      image_group_id: I1KG8649
      title: ''
      volume_number: 42
      total_pages: 630
      base_file: v042.txt
    7517892d31a546db90f06ec170e4f2ea:
      image_group_id: I1KG8650
      title: ''
      volume_number: 43
      total_pages: 646
      base_file: v043.txt
    99c7eb852c2b4a969426271afd2ea2dc:
      image_group_id: I1KG8651
      title: ''
      volume_number: 44
      total_pages: 716
      base_file: v044.txt
    48d654f8ab3846fa842cf4e820255662:
      image_group_id: I1KG8652
      title: ''
      volume_number: 45
      total_pages: 660
      base_file: v045.txt
    634baaff319843578cac615a398dbf77:
      image_group_id: I1KG8653
      title: ''
      volume_number: 46
      total_pages: 622
      base_file: v046.txt
    34b047ff78bd4060affde64c0051eb23:
      image_group_id: I1KG8654
      title: ''
      volume_number: 47
      total_pages: 618
      base_file: v047.txt
    895e3d8d19a24b3f9a15b782e0692439:
      image_group_id: I1KG8655
      title: ''
      volume_number: 48
      total_pages: 604
      base_file: v048.txt
    f98b03263eb34660a621411e0a9e5bd5:
      image_group_id: I1KG8656
      title: ''
      volume_number: 49
      total_pages: 610
      base_file: v049.txt
    5db8e37b98694fabb48be577d665e762:
      image_group_id: I1KG8657
      title: ''
      volume_number: 50
      total_pages: 680
      base_file: v050.txt
    008b24c6668d4c4597c186e73254d981:
      image_group_id: I1KG8658
      title: ''
      volume_number: 51
      total_pages: 666
      base_file: v051.txt
    65a3e188b4c5455a8f075e10977780d8:
      image_group_id: I1KG8659
      title: ''
      volume_number: 52
      total_pages: 622
      base_file: v052.txt
    fdd209e537b64a0da994b42b507b44b4:
      image_group_id: I1KG8660
      title: ''
      volume_number: 53
      total_pages: 828
      base_file: v053.txt
    f76e4bd214ae463b8dbe762ccc7b9f69:
      image_group_id: I1KG8661
      title: ''
      volume_number: 54
      total_pages: 752
      base_file: v054.txt
    8f23afa49b774d72be428fa5bbb49220:
      image_group_id: I1KG8662
      title: ''
      volume_number: 55
      total_pages: 808
      base_file: v055.txt
    cc4ef1b5faab4210bc2302221ab18e8f:
      image_group_id: I1KG8663
      title: ''
      volume_number: 56
      total_pages: 718
      base_file: v056.txt
    abd134efb9764d39922a0d34090c2f10:
      image_group_id: I1KG8664
      title: ''
      volume_number: 57
      total_pages: 460
      base_file: v057.txt
    e6e275721df14515be61008708861d83:
      image_group_id: I1KG8665
      title: ''
      volume_number: 58
      total_pages: 676
      base_file: v058.txt
    7c1cbda937fc41f4ae796eb728abf8d6:
      image_group_id: I1KG8666
      title: ''
      volume_number: 59
      total_pages: 610
      base_file: v059.txt
    4b566b4f1d9843ae9b55d942e7726a56:
      image_group_id: I1KG8667
      title: ''
      volume_number: 60
      total_pages: 442
      base_file: v060.txt
    7477c1f9c61245e1b3f452c5189795a3:
      image_group_id: I1KG8668
      title: ''
      volume_number: 61
      total_pages: 968
      base_file: v061.txt
    40b43c2f0d494e10a31083563b3377a7:
      image_group_id: I1KG8669
      title: ''
      volume_number: 62
      total_pages: 500
      base_file: v062.txt
    192e33dc1a4f4be383ff04cdcd41b844:
      image_group_id: I1KG8670
      title: ''
      volume_number: 63
      total_pages: 934
      base_file: v063.txt
    c6563ea15a5d4de5a2c70f313c00aabd:
      image_group_id: I1KG8671
      title: ''
      volume_number: 64
      total_pages: 520
      base_file: v064.txt
    59f98029ba7f4206b9753eebbe26f3b3:
      image_group_id: I1KG8672
      title: ''
      volume_number: 65
      total_pages: 479
      base_file: v065.txt
    8c7baa3cb9854248bc789a4a3b6f24e6:
      image_group_id: I1KG8673
      title: ''
      volume_number: 66
      total_pages: 518
      base_file: v066.txt
    1ecc8aa488b341a1bb5b13a3b173ccf8:
      image_group_id: I1KG8674
      title: ''
      volume_number: 67
      total_pages: 1160
      base_file: v067.txt
    dd177a9594cf4d768504ee9d74fd6690:
      image_group_id: I1KG8675
      title: ''
      volume_number: 68
      total_pages: 712
      base_file: v068.txt
    8ff34615488f4ec7ba1fc96749118b6d:
      image_group_id: I1KG8676
      title: ''
      volume_number: 69
      total_pages: 564
      base_file: v069.txt
    d93b403095ab45aaa53b3318dc88f423:
      image_group_id: I1KG8677
      title: ''
      volume_number: 70
      total_pages: 700
      base_file: v070.txt
    4819803698fb4a59a0cf8654643d4cbf:
      image_group_id: I1KG8678
      title: ''
      volume_number: 71
      total_pages: 518
      base_file: v071.txt
    74045899fd5142d7a1c0150c9f0352f2:
      image_group_id: I1KG8679
      title: ''
      volume_number: 72
      total_pages: 560
      base_file: v072.txt
    a47dc4a4c0644a7a965c8a075ad03da4:
      image_group_id: I1KG8680
      title: ''
      volume_number: 73
      total_pages: 606
      base_file: v073.txt
    8969ca5d26314469a29e016940bf07f8:
      image_group_id: I1KG8681
      title: ''
      volume_number: 74
      total_pages: 592
      base_file: v074.txt
    8ea11efe6a154a89a13218f1f630e5a6:
      image_group_id: I1KG8682
      title: ''
      volume_number: 75
      total_pages: 694
      base_file: v075.txt
    af6d42c41127484d80285f969a0cd843:
      image_group_id: I1KG8683
      title: ''
      volume_number: 76
      total_pages: 866
      base_file: v076.txt
    08612f59f3894266a89d924b7c3b417a:
      image_group_id: I1KG8684
      title: ''
      volume_number: 77
      total_pages: 874
      base_file: v077.txt
    229c57dfa6914affabd774d3c4d710ec:
      image_group_id: I1KG8685
      title: ''
      volume_number: 78
      total_pages: 576
      base_file: v078.txt
    9ded7555298f4837b078f95f4d7a8cc5:
      image_group_id: I1KG8686
      title: ''
      volume_number: 79
      total_pages: 568
      base_file: v079.txt
    af5cc42e66914135894ad55734e27d38:
      image_group_id: I1KG8687
      title: ''
      volume_number: 80
      total_pages: 580
      base_file: v080.txt
    66284a0d693d4985bf02ffef248c5c86:
      image_group_id: I1KG8688
      title: ''
      volume_number: 81
      total_pages: 572
      base_file: v081.txt
    252513b24df44e9990d52fffc5f0acd9:
      image_group_id: I1KG8689
      title: ''
      volume_number: 82
      total_pages: 508
      base_file: v082.txt
    c0638a8be7ab40ca8de9f0d406e3f4f0:
      image_group_id: I1KG8690
      title: ''
      volume_number: 83
      total_pages: 726
      base_file: v083.txt
    f7008f76e4c34e2da4314e0da5c34331:
      image_group_id: I1KG8691
      title: ''
      volume_number: 84
      total_pages: 832
      base_file: v084.txt
    74f0d40ab2b2481f930d771435d48325:
      image_group_id: I1KG8692
      title: ''
      volume_number: 85
      total_pages: 714
      base_file: v085.txt
    0f28958ae2cf4d8cbc68534bcff0c372:
      image_group_id: I1KG8693
      title: ''
      volume_number: 86
      total_pages: 586
      base_file: v086.txt
    aa007bef2f9c4b47abb68f12354b6386:
      image_group_id: I1KG8694
      title: ''
      volume_number: 87
      total_pages: 562
      base_file: v087.txt
    f47ee294588b4812b3a28bff8558922f:
      image_group_id: I1KG8695
      title: ''
      volume_number: 88
      total_pages: 604
      base_file: v088.txt
    fdc37ab3148b4f68bdb665e42804567c:
      image_group_id: I1KG8696
      title: ''
      volume_number: 89
      total_pages: 652
      base_file: v089.txt
    877e46780a8d46f9893ba04efc441998:
      image_group_id: I1KG8697
      title: ''
      volume_number: 90
      total_pages: 980
      base_file: v090.txt
    1fbf425ee5144a18a333232d6bd2c9ac:
      image_group_id: I1KG8698
      title: ''
      volume_number: 91
      total_pages: 920
      base_file: v091.txt
    e9eb048d77ff4c2b9a56dbcd9d214df2:
      image_group_id: I1KG8699
      title: ''
      volume_number: 92
      total_pages: 536
      base_file: v092.txt
    f540c4e86b0e4d72ab1714029db60868:
      image_group_id: I1KG8700
      title: ''
      volume_number: 93
      total_pages: 632
      base_file: v093.txt
    1e621d69e6164d65a24f60f9772efe96:
      image_group_id: I1KG8701
      title: ''
      volume_number: 94
      total_pages: 602
      base_file: v094.txt
    c7245500f6b34a889c1951c508165e35:
      image_group_id: I1KG8702
      title: ''
      volume_number: 95
      total_pages: 572
      base_file: v095.txt
    6e49dc60e7cc43669cd6712ad1179167:
      image_group_id: I1KG8703
      title: ''
      volume_number: 96
      total_pages: 574
      base_file: v096.txt
    fec169cd96744d4b9251637f4bf06244:
      image_group_id: I1KG8704
      title: ''
      volume_number: 97
      total_pages: 734
      base_file: v097.txt
    369599a6ad95430b878c88d9b0fb2368:
      image_group_id: I1KG8705
      title: ''
      volume_number: 98
      total_pages: 566
      base_file: v098.txt
    f400a8434ab14693a7301b04d1a67604:
      image_group_id: I1KG8706
      title: ''
      volume_number: 99
      total_pages: 466
      base_file: v099.txt
    17ab38be62e548758d9ded4d1867e3eb:
      image_group_id: I1KG8707
      title: ''
      volume_number: 100
      total_pages: 932
      base_file: v100.txt
    363757e4378b4852b97efdb8c6fa8675:
      image_group_id: I1KG8708
      title: ''
      volume_number: 101
      total_pages: 0
      base_file: v101.txt
    bd0c72fa6cb84bb3b57eab005e0c6181:
      image_group_id: I1KG8709
      title: ''
      volume_number: 102
      total_pages: 710
      base_file: v102.txt
    993f3c09cce641a6a636ce414b4d5fe7:
      image_group_id: I1KG8710
      title: ''
      volume_number: 103
      total_pages: 960
      base_file: v103.txt
    10d549ceecf6489a8f5c334619248a4f:
      image_group_id: I1KG8711
      title: ''
      volume_number: 104
      total_pages: 752
      base_file: v104.txt
    054687067a1e48678ff3bfc5d4e4123b:
      image_group_id: I1KG8712
      title: ''
      volume_number: 105
      total_pages: 660
      base_file: v105.txt
    62b2077c0f1e431a9c730db894348000:
      image_group_id: I1KG8713
      title: ''
      volume_number: 106
      total_pages: 548
      base_file: v106.txt
    3c1b551b49fa4069a3a6a3040c9a9c5f:
      image_group_id: I1KG8714
      title: ''
      volume_number: 107
      total_pages: 702
      base_file: v107.txt
    26321d06adcd4766954ceaedf475d6a3:
      image_group_id: I1KG8715
      title: ''
      volume_number: 108
      total_pages: 478
      base_file: v108.txt
    5dd967306ce945ecbdbbbe3ef0817f23:
      image_group_id: I1KG8716
      title: ''
      volume_number: 109
      total_pages: 590
      base_file: v109.txt
    75c9fa047c30435abc8e40af2cea76d2:
      image_group_id: I1KG8717
      title: ''
      volume_number: 110
      total_pages: 788
      base_file: v110.txt
